--1)
--SELECT STUDENT.*,RESULT.* FROM STUDENT JOIN RESULT ON STUDENT.RNO=RESULT.RNO

--2)
--SELECT STUDENT.*,RESULT.SPI FROM STUDENT LEFT OUTER JOIN RESULT ON STUDENT.RNO=RESULT.RNO WHERE STUDENT.BRANCH = 'CE'

--3)
--SELECT STUDENT.*,RESULT.SPI FROM STUDENT LEFT JOIN RESULT ON STUDENT.RNO=RESULT.RNO WHERE STUDENT.BRANCH <> 'EC'

--4)
--SELECT STUDENT.BRANCH,AVG(RESULT.SPI) FROM STUDENT LEFT OUTER JOIN RESULT ON STUDENT.RNO=RESULT.RNO GROUP BY STUDENT.BRANCH

--5)
--SELECT STUDENT.BRANCH,AVG(RESULT.SPI) FROM STUDENT INNER JOIN RESULT ON STUDENT.RNO=RESULT.RNO GROUP BY STUDENT.BRANCH ORDER BY AVG(RESULT.SPI) ASC

--6)
SELECT STUDENT.BRANCH,AVG(RESULT.SPI) FROM STUDENT INNER JOIN RESULT ON STUDENT.RNO=RESULT.RNO WHERE STUDENT.BRANCH BETWEEN CE AND ME GROUP BY STUDENT.BRANCH 