--1)
--SELECT MAX(SALARY) AS MAXIMUM,MIN(SALARY) AS MINIMUM,SUM(SALARY) AS TOTAL_SAL,AVG(SALARY) AS AVERAGE_SAL FROM EMPLOYEE

--2)
--SELECT COUNT(EID) FROM EMPLOYEE

--3)
--SELECT MAX(SALARY) FROM EMPLOYEE
--WHERE DEPT = 'IT'

--4)
--SELECT  COUNT(DISTINCT CITY) FROM EMPLOYEE

--5)
--SELECT DISTINCT CITY,COUNT(ENAME) FROM EMPLOYEE
--group by city

--6)
--select Distinct city,count(ename) from employee
--group by city
--having count(ename) >1

--7)
--select Distinct dept,sum(salary) from employee
--group by dept

--8)
--SELECT AVG(SALARY) FROM EMPLOYEE
--GROUP BY DEPT

--9)
--SELECT MIN(SALARY) FROM EMPLOYEE
--GROUP BY CITY
--HAVING CITY = 'AHMEDABAD'

--10)
--SELECT DISTINCT DEPT,SUM(SALARY) FROM EMPLOYEE
--WHERE CITY ='RAJKOT'
--GROUP BY DEPT
--HAVING SUM(SALARY) > 50000

--11)
--SELECT COUNT(ENAME) FROM EMPLOYEE
--WHERE CITY = 'RAJKOT'
--GROUP BY CITY

--12)
--SELECT MAX(SALARY)-MIN(SALARY) FROM EMPLOYEE
